### ISSUE TITLE
Documenting Default Parameters?

### ISSUE THREAD

**Issue by insertinterestingnamehere** [losalamos/tycho2#15]
Hi, I'm part of a group at UT Austin looking at potential optimizations for sweeps in the irregular setting on both CPUs and GPUs. We want to use this mini app as a baseline for performance comparisons with a similar code we're developing right now, but it's not clear what parameter ranges are actually meaningful targets for optimization.

The technical report on Tycho 2 includes a weak scaling plot, but it doesn't describe the parameters and data used to generate it. Would it be at all possible to document how to reproduce the experiments shown there? By looking through the build instructions and user guide I've been able to get Tycho 2 to build and can run it on the cube datasets in the utils directory with a patched version of examples/input.deck.example to specify the parameters. I'm still not sure what parameter combinations to focus on when evaluating/developing our implementation though.

**Comment by berselius** [comment]
Hi! We're actually in the process of refreshing tycho2 - the original developer has left lanl and I'm picking up the lead on it. I'll dig in to some of Kris's documentation and see if I can answer your questions. 

P.S. what group are you with at UT? I was at ICES a while back in my postdoc days.

**Comment by insertinterestingnamehere** [comment]
Thanks! That'd be great! I'm working with Keshav Pingali, though on this project I've been working more directly with Martin Burtscher from Texas State since he has a lot of experience optimizing this kind of thing on GPUs. We noticed sweeps a while back as a potential application of some of our irregular graph processing work. I'm looking into it a lot more right now as a part of the new PSAAP center that was just established here. Tycho 2 is of particular interest to us since it's the only sweeps mini-app that I'm aware of that handles anything other than a regular grid.

**Comment by warsa** [comment]
I can certainly help as I have alot of familiarity with tycho2. I would recommend working on the cmake_kokkos branch, as that has several enhancements. As far as the parameters used in the computations, we used an array of tools to generate a sequence of meshes that are available in the repo. It's been a while since I've done anything with tycho2, but I would be interested in reviving our efforts and would be happy to assist as time permits.

**Comment by insertinterestingnamehere** [comment]
Thanks, that's really helpful. I'll take a look at that branch and see if I can get it working locally too.

Also thanks for the heads up about the utilities. Thus far I've figured out how to use the RefineSerialMesh utility, so I can generate larger meshes. I need to experiment some more with the mesh refinement utilities. I'm still lost as to what to put in the input.deck and how many angle groups to use.

**Comment by insertinterestingnamehere** [comment]
Also pinging @burtscher so he can follow the discussion here too.

**Comment by warsa** [comment]
Ian,

Sorry, nevermind, I see you already know this: If you look at this branch, there is a sample input and a build.txt file with example on how to configure and compile:
https://github.com/lanl/tycho2/tree/cmake_kokkos
I may be able to dig up the params used in the results to which you refer, let me see what I can find, if anything.

**Comment by warsa** [comment]
Can you please point me to the scaling plot or table? If I remember correctly, when we looked at problems for Kris to evaluate, we did two-region problems with snOrder 8 and sigmaT = 10 sigma_S = 5. For a useful investigation, the snOrder should be something like 6-16, and the number of groups would be something like 30-100, depending on what you're looking at it. If it's just parallel graph traversal alone, then the number of groups isn't particularly relevant, although it may be for GPU, depending on the implementation.

**Comment by insertinterestingnamehere** [comment]
Sorry for any confusion, it's not a plot, just a weak scaling table. It's toward the top left of the second page of actual content (page 4 of the pdf). The technical report I'm referring to is https://permalink.lanl.gov/object/tr?what=info:lanl-repo/lareport/LA-UR-16-27030.

**Comment by insertinterestingnamehere** [comment]
As far as we know right now, the number of frequency groups does matter for the GPU, but we're looking into that further. Do you remember anything about what constitutes a reasonable range of values for the number of angle groups?

**Comment by warsa** [comment]
Oh yes, thanks, that's the highlight we wrote some time ago.

Yes, as I said, I would imagine number of group will affect performance on GPUS. For example, we have an implementation where the threadblocks are over groups. A fair number to scale over would over the range I suggested, 100-300 and quadrature order snOrder in the tycho2 input on the order of 6-16, although going as high as 32 wouldn't typically be unreasonable.

**Comment by warsa** [comment]
Note that in 3D, for snOrder N, there are N*(N+2) angles for the quadrature arrangement in tycho2. Our implementation is not MPI parallel-in-angle or energy, only in space.

**Comment by insertinterestingnamehere** [comment]
Okay thanks, this makes sense. I had missed the relationship between the number of directions and the snOrder parameter.

**Comment by insertinterestingnamehere** [comment]
FWIW, here's where we're at on our end: I've already written a simplified sweeps code and we've spent some time optimizing that. It was designed more as an initial pass to see if this is a problem we can handle well. It relies on lots of simplifying assumptions like working on a regular grid and having each angle/frequency scatter out evenly into every angle/frequency. We've avoided relying on those assumptions for optimizing though since our ultimate goal is to run this on an irregular problem with more realistic inputs. Right now I'm working to update our code to match the mathematical problem solved by Tycho 2 so that we can focus on something more realistic.

**Comment by insertinterestingnamehere** [comment]
I think the parameter ranges you suggested are all I need for now. Is the issue tracker an okay place to report back with further questions as they arise or is somewhere else better?

**Comment by warsa** [comment]
This is fine, although email works too. I should tell you that we do not have a true isotropic scattering in tycho2 as we were primarily interested in sweeps. If you need something like that, I think we could get it in fairly quickly.

**Comment by insertinterestingnamehere** [comment]
Thanks! The isotropy was just to simplify our initial pass since we weren't yet sure what kind of anisotropy would be appropriate. We ultimately want to handle the anisotropic case.

**Comment by warsa** [comment]
We also don't have real group-to-group scattering in there, but again, also easy to add if you're interested.

**Comment by insertinterestingnamehere** [comment]
I'm not entirely sure what you mean. Do you mean that currently scattering only takes place between diffirent directions with the same frequency group? That's an area where we're mostly interested in doing whatever would be most useful for/representative of a full simulation that needs this kind of thing, whether it's no scattering between frequency groups, isotropic scattering between frequency groups, or scattering based off of actual coefficients of some kind. We're coming at this from the CS/PL research standpoint, so as long as the app is a realistic use-case we're happy.

**Comment by insertinterestingnamehere** [comment]
Also, here I'm seeing two different possible ranges for the number of frequency groups. Were you recommending 30-100 or 100-300?

**Comment by warsa** [comment]
Approx 30 would be typical but can be as many as around 300.

**Comment by insertinterestingnamehere** [comment]
Great, thank you!

**Comment by warsa** [comment]
I meant to also reply to the previous question. The way it is currently implemented, yes scattering is within-group only and isotropic. Again, this is not typical but is an oft-used approximation.

**Comment by insertinterestingnamehere** [comment]
Got it. Thank you. We'd be happy to have something more accurate in general, but it sounds like that's not a critical difference. As I said earlier, the main important thing for our work is just that it be a realistic performance proxy.

**Comment by insertinterestingnamehere** [comment]
Okay, I'm working on this again (got delayed with several other projects for a bit). I noticed that (provided I'm not missing anything), it's possible to go from the current fluxes to the scattering come into each flux direction/frequency via a batched gemm call (which cublas has available now). Is this currently done? Is there any reason this isn't currently done? I remember some of the older papers on sweeps talk about being heavily constrained by memory space, and precomputing the radiation scattering into each direction will require us to either store the input scattering as a separate value or do some sort of clever in-place storage work, but being able to call into cublas for so much of the computation is appealing.

**Comment by david8dixon** [comment]
I don't believe we make any specific use of cudablas anywhere (not to say we shouldn't). I suspect you will find that most of the GPU related effort has been almost entirely devoted to the graph traversal. It might be feasible to precompute but we have issues with memory footprint on CPUs and it gets worse on the GPU.

I am speculating but I suspect the biggest gains will come from optimizing the graph traversal. A profile would probably confirm this. With an optimal traversal, the next thing I would probably look at is how the data layout impacts performance. We thread over energy and each energy requires non-trivial amounts of data  and I don't know how much of it can be reused negatively impacting cache contention. For a cell-angle pair threads can reuse space and angle data but then all of the energy dependent data (solution vectors, source vectors and physical data) across threads introduces strided access.

**Comment by insertinterestingnamehere** [comment]
Great, thanks for clarifying. We'll be sure to make sure our solution is aware of the space constraints. Our current (simplified) version is only threading over directions and then looping over the energy-specific data in each thread. Focusing on optimizing the graph traversal makes sense. On the other hand, it'd be nice to offload as much of the computation as we can to cublas since vendor libraries continue to be improved and often include more architecture-specific optimizations.
